spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/gestao_vagas}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update

security:
  token:
    secret:
      jwt: JAVAGAS_@123
      company: JAVAGAS_@123#COMPANY
      candidate: JAVAGAS_@123#CANDIDATE

management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,metrics,prometheus
